name: "workflow run test"

on:
  workflow_run:
    workflows: main
    branches: main
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: |
          echo ${{ github.event.workflow_run.conclusion }}

  test_its_okay:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: |
          echo ${{ github.event.workflow_run.conclusion }}
