name: "workflow run test"

on:
  workflow_run:
    workflows: ["main"]
    branches: main
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: |
          echo "test"
